@api = http://localhost:3020/api/pwa

//GET ALL INSTITUTES
GET {{api}}/institutes

//POST INSTITUTE
POST {{api}}
Content-Type: application/json

{
  "DesInstituto": "prueba",
  "IdInstitutesOK": 743
}